const os = require('os')
console.log(os.arch())
console.log(os.freemem())
console.log(os.hostname())
console.log(os.availableParallelism())
console.log(os.cpus())
console.log(os.endianness())
console.log(os.getPriority())